-- AuthZ Engine Database Initialization
-- Enables pgvector and creates schema for agentic authorization

-- Enable pgvector extension for semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- Decisions table - stores all authorization decisions for learning
CREATE TABLE IF NOT EXISTS authz_decisions (
    id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,

    -- Principal info
    principal_id TEXT NOT NULL,
    principal_roles JSONB NOT NULL,
    principal_attributes JSONB,

    -- Resource info
    resource_kind TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    resource_attributes JSONB,

    -- Decision details
    actions JSONB NOT NULL,
    results JSONB NOT NULL,
    derived_roles JSONB,
    matched_policies JSONB,

    -- Agent enrichment
    enrichment_data JSONB,
    anomaly_score FLOAT,
    risk_factors JSONB,

    -- Vector embedding for semantic search (1536 = OpenAI ada-002)
    embedding VECTOR(1536),

    -- Outcome tracking (for learning)
    outcome JSONB,
    outcome_recorded_at TIMESTAMPTZ,
    feedback JSONB,
    feedback_recorded_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_decisions_principal ON authz_decisions(principal_id);
CREATE INDEX IF NOT EXISTS idx_decisions_resource ON authz_decisions(resource_kind, resource_id);
CREATE INDEX IF NOT EXISTS idx_decisions_timestamp ON authz_decisions(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_anomaly ON authz_decisions(anomaly_score) WHERE anomaly_score IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_decisions_request_id ON authz_decisions(request_id);

-- Vector similarity index for semantic search
CREATE INDEX IF NOT EXISTS idx_decisions_embedding ON authz_decisions
    USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Anomalies table - detected by GUARDIAN agent
CREATE TABLE IF NOT EXISTS authz_anomalies (
    id TEXT PRIMARY KEY,
    detected_at TIMESTAMPTZ NOT NULL,

    -- Anomaly classification
    type TEXT NOT NULL,
    severity TEXT NOT NULL,

    -- Context
    principal_id TEXT NOT NULL,
    resource_kind TEXT,
    action TEXT,

    -- Details
    description TEXT NOT NULL,
    score FLOAT NOT NULL,
    evidence JSONB NOT NULL,
    baseline JSONB NOT NULL,
    observed JSONB NOT NULL,

    -- Resolution tracking
    status TEXT NOT NULL DEFAULT 'open',
    resolved_at TIMESTAMPTZ,
    resolution TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_anomalies_principal ON authz_anomalies(principal_id);
CREATE INDEX IF NOT EXISTS idx_anomalies_status ON authz_anomalies(status);
CREATE INDEX IF NOT EXISTS idx_anomalies_detected ON authz_anomalies(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_anomalies_severity ON authz_anomalies(severity);

-- Patterns table - discovered by ANALYST agent
CREATE TABLE IF NOT EXISTS authz_patterns (
    id TEXT PRIMARY KEY,
    discovered_at TIMESTAMPTZ NOT NULL,
    last_updated TIMESTAMPTZ NOT NULL,

    -- Pattern details
    type TEXT NOT NULL,
    confidence FLOAT NOT NULL,
    sample_size INT NOT NULL,
    description TEXT NOT NULL,
    conditions JSONB NOT NULL,

    -- Suggestions
    suggested_policy_rule TEXT,
    suggested_optimization TEXT,

    -- Validation
    validated_at TIMESTAMPTZ,
    validated_by TEXT,
    is_approved BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_patterns_type ON authz_patterns(type);
CREATE INDEX IF NOT EXISTS idx_patterns_approved ON authz_patterns(is_approved);
CREATE INDEX IF NOT EXISTS idx_patterns_confidence ON authz_patterns(confidence DESC);

-- Actions table - executed by ENFORCER agent
CREATE TABLE IF NOT EXISTS authz_actions (
    id TEXT PRIMARY KEY,
    triggered_at TIMESTAMPTZ NOT NULL,

    -- Action details
    type TEXT NOT NULL,
    priority TEXT NOT NULL,
    triggered_by JSONB NOT NULL,

    -- Execution tracking
    status TEXT NOT NULL DEFAULT 'pending',
    executed_at TIMESTAMPTZ,
    result JSONB,

    -- Rollback support
    can_rollback BOOLEAN DEFAULT FALSE,
    rolled_back_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_actions_status ON authz_actions(status);
CREATE INDEX IF NOT EXISTS idx_actions_type ON authz_actions(type);
CREATE INDEX IF NOT EXISTS idx_actions_triggered ON authz_actions(triggered_at DESC);

-- Explanations table - generated by ADVISOR agent (cached)
CREATE TABLE IF NOT EXISTS authz_explanations (
    id TEXT PRIMARY KEY,
    request_hash TEXT NOT NULL UNIQUE,
    generated_at TIMESTAMPTZ NOT NULL,

    -- Explanation content
    summary TEXT NOT NULL,
    factors JSONB NOT NULL,
    natural_language TEXT,
    recommendations JSONB,
    path_to_allow JSONB,

    -- Cache metadata
    expires_at TIMESTAMPTZ,
    hit_count INT DEFAULT 1,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_explanations_hash ON authz_explanations(request_hash);
CREATE INDEX IF NOT EXISTS idx_explanations_expires ON authz_explanations(expires_at);

-- Principal baselines - computed by GUARDIAN agent
CREATE TABLE IF NOT EXISTS authz_baselines (
    principal_id TEXT PRIMARY KEY,
    computed_at TIMESTAMPTZ NOT NULL,

    -- Statistics
    period TEXT NOT NULL,
    avg_requests_per_hour FLOAT NOT NULL,
    unique_resources INT NOT NULL,
    common_actions JSONB NOT NULL,
    common_time_ranges JSONB NOT NULL,
    denial_rate FLOAT,

    -- Raw data for recomputation
    sample_count INT NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Audit log for all agent operations
CREATE TABLE IF NOT EXISTS authz_audit_log (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- What happened
    agent_type TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    event_type TEXT NOT NULL,

    -- Context
    principal_id TEXT,
    resource_kind TEXT,
    resource_id TEXT,

    -- Details
    payload JSONB,
    correlation_id TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON authz_audit_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_agent ON authz_audit_log(agent_type);
CREATE INDEX IF NOT EXISTS idx_audit_principal ON authz_audit_log(principal_id);
CREATE INDEX IF NOT EXISTS idx_audit_correlation ON authz_audit_log(correlation_id);

-- Partitioning for decisions table (by month) - for large deployments
-- Uncomment if needed:
-- CREATE TABLE authz_decisions_partitioned (LIKE authz_decisions INCLUDING ALL)
--     PARTITION BY RANGE (timestamp);

-- Function to auto-cleanup old data
CREATE OR REPLACE FUNCTION cleanup_old_data(retention_days INT DEFAULT 90)
RETURNS void AS $$
BEGIN
    -- Delete old decisions
    DELETE FROM authz_decisions
    WHERE timestamp < NOW() - (retention_days || ' days')::INTERVAL;

    -- Delete old audit logs
    DELETE FROM authz_audit_log
    WHERE timestamp < NOW() - (retention_days || ' days')::INTERVAL;

    -- Delete expired explanations
    DELETE FROM authz_explanations
    WHERE expires_at < NOW();

    -- Delete resolved anomalies older than retention
    DELETE FROM authz_anomalies
    WHERE status IN ('resolved', 'false_positive')
    AND resolved_at < NOW() - (retention_days || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Grant permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authz;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authz;

-- Initial data: Default pattern types
INSERT INTO authz_patterns (id, discovered_at, last_updated, type, confidence, sample_size, description, conditions, is_approved)
VALUES
    ('system-default-admin', NOW(), NOW(), 'role_cluster', 1.0, 0, 'System default: Admin users have full access', '[]'::jsonb, true)
ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE authz_decisions IS 'Authorization decisions for pattern learning and anomaly detection';
COMMENT ON TABLE authz_anomalies IS 'Anomalies detected by GUARDIAN agent';
COMMENT ON TABLE authz_patterns IS 'Access patterns discovered by ANALYST agent';
COMMENT ON TABLE authz_actions IS 'Enforcement actions executed by ENFORCER agent';
COMMENT ON TABLE authz_explanations IS 'Cached explanations generated by ADVISOR agent';
