// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/authz/v1/authz.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Effect represents the authorization decision
type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED Effect = 0
	Effect_EFFECT_ALLOW       Effect = 1
	Effect_EFFECT_DENY        Effect = 2
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_ALLOW",
		2: "EFFECT_DENY",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"EFFECT_ALLOW":       1,
		"EFFECT_DENY":        2,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_authz_v1_authz_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_api_proto_authz_v1_authz_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

type SourceType int32

const (
	SourceType_SOURCE_TYPE_UNSPECIFIED SourceType = 0
	SourceType_SOURCE_TYPE_FILE        SourceType = 1
	SourceType_SOURCE_TYPE_URL         SourceType = 2
	SourceType_SOURCE_TYPE_INLINE      SourceType = 3
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_FILE",
		2: "SOURCE_TYPE_URL",
		3: "SOURCE_TYPE_INLINE",
	}
	SourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_FILE":        1,
		"SOURCE_TYPE_URL":         2,
		"SOURCE_TYPE_INLINE":      3,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_authz_v1_authz_proto_enumTypes[1].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_api_proto_authz_v1_authz_proto_enumTypes[1]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

// CheckRequest represents an authorization check request
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The principal (user/service) requesting access
	Principal *Principal `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	// The resource being accessed
	Resource *Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	// Actions being requested (e.g., "read", "write", "delete")
	Actions []string `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	// Additional context for policy evaluation
	Context *structpb.Struct `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	// Include detailed metadata in response
	IncludeMetadata bool `protobuf:"varint,6,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckRequest) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *CheckRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckRequest) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CheckRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

// Principal represents the entity requesting access
type Principal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier (e.g., user ID, service account)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Roles assigned to the principal
	Roles []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// Additional attributes for ABAC
	Attributes *structpb.Struct `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Hierarchical scope for this principal (e.g., "acme.corp.engineering")
	Scope         string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Principal) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Principal) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// Resource represents the resource being accessed
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type/kind (e.g., "document", "avatar", "payout")
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Unique resource identifier
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Resource attributes for ABAC
	Attributes *structpb.Struct `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Hierarchical scope for this resource (e.g., "acme.corp.engineering")
	Scope         string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Resource) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// CheckResponse contains the authorization decision
type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoed request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Results per action
	Results map[string]*ActionResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Evaluation metadata (if requested)
	Metadata      *ResponseMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckResponse) GetResults() map[string]*ActionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CheckResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ActionResult contains the decision for a single action
type ActionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authorization effect
	Effect Effect `protobuf:"varint,1,opt,name=effect,proto3,enum=authz.v1.Effect" json:"effect,omitempty"`
	// Name of the policy that matched
	Policy string `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// Name of the rule within the policy
	Rule string `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	// Whether a matching rule was found
	Matched bool `protobuf:"varint,4,opt,name=matched,proto3" json:"matched,omitempty"`
	// Additional metadata about the decision
	Meta          map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{4}
}

func (x *ActionResult) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

func (x *ActionResult) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *ActionResult) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ActionResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ActionResult) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ResponseMetadata contains evaluation details
type ResponseMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time taken to evaluate (microseconds)
	EvaluationDurationUs float64 `protobuf:"fixed64,1,opt,name=evaluation_duration_us,json=evaluationDurationUs,proto3" json:"evaluation_duration_us,omitempty"`
	// Number of policies evaluated
	PoliciesEvaluated int32 `protobuf:"varint,2,opt,name=policies_evaluated,json=policiesEvaluated,proto3" json:"policies_evaluated,omitempty"`
	// Names of policies that matched
	MatchedPolicies []string `protobuf:"bytes,3,rep,name=matched_policies,json=matchedPolicies,proto3" json:"matched_policies,omitempty"`
	// Cache hit or miss
	CacheHit bool `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	// Scope resolution information
	ScopeResolution *ScopeResolution `protobuf:"bytes,5,opt,name=scope_resolution,json=scopeResolution,proto3" json:"scope_resolution,omitempty"`
	// Phase 3: Policy resolution info
	PolicyResolution *PolicyResolution `protobuf:"bytes,6,opt,name=policy_resolution,json=policyResolution,proto3" json:"policy_resolution,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseMetadata) GetEvaluationDurationUs() float64 {
	if x != nil {
		return x.EvaluationDurationUs
	}
	return 0
}

func (x *ResponseMetadata) GetPoliciesEvaluated() int32 {
	if x != nil {
		return x.PoliciesEvaluated
	}
	return 0
}

func (x *ResponseMetadata) GetMatchedPolicies() []string {
	if x != nil {
		return x.MatchedPolicies
	}
	return nil
}

func (x *ResponseMetadata) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *ResponseMetadata) GetScopeResolution() *ScopeResolution {
	if x != nil {
		return x.ScopeResolution
	}
	return nil
}

func (x *ResponseMetadata) GetPolicyResolution() *PolicyResolution {
	if x != nil {
		return x.PolicyResolution
	}
	return nil
}

// ScopeResolution contains scope resolution result
type ScopeResolution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope that matched (or "(global)" for unscoped)
	MatchedScope string `protobuf:"bytes,1,opt,name=matched_scope,json=matchedScope,proto3" json:"matched_scope,omitempty"`
	// Scopes checked during resolution (most to least specific)
	InheritanceChain []string `protobuf:"bytes,2,rep,name=inheritance_chain,json=inheritanceChain,proto3" json:"inheritance_chain,omitempty"`
	// Whether a scoped policy was found
	ScopedPolicyMatched bool `protobuf:"varint,3,opt,name=scoped_policy_matched,json=scopedPolicyMatched,proto3" json:"scoped_policy_matched,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScopeResolution) Reset() {
	*x = ScopeResolution{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeResolution) ProtoMessage() {}

func (x *ScopeResolution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeResolution.ProtoReflect.Descriptor instead.
func (*ScopeResolution) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{6}
}

func (x *ScopeResolution) GetMatchedScope() string {
	if x != nil {
		return x.MatchedScope
	}
	return ""
}

func (x *ScopeResolution) GetInheritanceChain() []string {
	if x != nil {
		return x.InheritanceChain
	}
	return nil
}

func (x *ScopeResolution) GetScopedPolicyMatched() bool {
	if x != nil {
		return x.ScopedPolicyMatched
	}
	return false
}

// PrincipalSelector for principal policies (Phase 3)
type PrincipalSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific principal ID (e.g., "user:alice")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Match ANY of these roles
	Roles []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// Principal's scope context
	Scope         string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrincipalSelector) Reset() {
	*x = PrincipalSelector{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalSelector) ProtoMessage() {}

func (x *PrincipalSelector) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalSelector.ProtoReflect.Descriptor instead.
func (*PrincipalSelector) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{7}
}

func (x *PrincipalSelector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrincipalSelector) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *PrincipalSelector) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// ResourceSelector for principal policies (Phase 3)
type ResourceSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource kind (supports wildcard *)
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Scope pattern (supports ** wildcard)
	Scope         string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSelector) Reset() {
	*x = ResourceSelector{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSelector) ProtoMessage() {}

func (x *ResourceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSelector.ProtoReflect.Descriptor instead.
func (*ResourceSelector) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceSelector) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceSelector) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// PolicyResolution metadata (Phase 3)
type PolicyResolution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether principal policies matched
	PrincipalPoliciesMatched bool `protobuf:"varint,1,opt,name=principal_policies_matched,json=principalPoliciesMatched,proto3" json:"principal_policies_matched,omitempty"`
	// Whether resource policies matched
	ResourcePoliciesMatched bool `protobuf:"varint,2,opt,name=resource_policies_matched,json=resourcePoliciesMatched,proto3" json:"resource_policies_matched,omitempty"`
	// Evaluation order (e.g., ["principal-specific", "resource-scoped"])
	EvaluationOrder []string `protobuf:"bytes,3,rep,name=evaluation_order,json=evaluationOrder,proto3" json:"evaluation_order,omitempty"`
	// Nested scope resolution info
	ScopeResolution *ScopeResolution `protobuf:"bytes,4,opt,name=scope_resolution,json=scopeResolution,proto3" json:"scope_resolution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyResolution) Reset() {
	*x = PolicyResolution{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResolution) ProtoMessage() {}

func (x *PolicyResolution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResolution.ProtoReflect.Descriptor instead.
func (*PolicyResolution) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{9}
}

func (x *PolicyResolution) GetPrincipalPoliciesMatched() bool {
	if x != nil {
		return x.PrincipalPoliciesMatched
	}
	return false
}

func (x *PolicyResolution) GetResourcePoliciesMatched() bool {
	if x != nil {
		return x.ResourcePoliciesMatched
	}
	return false
}

func (x *PolicyResolution) GetEvaluationOrder() []string {
	if x != nil {
		return x.EvaluationOrder
	}
	return nil
}

func (x *PolicyResolution) GetScopeResolution() *ScopeResolution {
	if x != nil {
		return x.ScopeResolution
	}
	return nil
}

// CheckBatchRequest contains multiple check requests
type CheckBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*CheckRequest        `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBatchRequest) Reset() {
	*x = CheckBatchRequest{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBatchRequest) ProtoMessage() {}

func (x *CheckBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBatchRequest.ProtoReflect.Descriptor instead.
func (*CheckBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{10}
}

func (x *CheckBatchRequest) GetRequests() []*CheckRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// CheckBatchResponse contains multiple check responses
type CheckBatchResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Responses []*CheckResponse       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	// Total batch processing time (microseconds)
	TotalDurationUs float64 `protobuf:"fixed64,2,opt,name=total_duration_us,json=totalDurationUs,proto3" json:"total_duration_us,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckBatchResponse) Reset() {
	*x = CheckBatchResponse{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBatchResponse) ProtoMessage() {}

func (x *CheckBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBatchResponse.ProtoReflect.Descriptor instead.
func (*CheckBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{11}
}

func (x *CheckBatchResponse) GetResponses() []*CheckResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *CheckBatchResponse) GetTotalDurationUs() float64 {
	if x != nil {
		return x.TotalDurationUs
	}
	return 0
}

// LoadPoliciesRequest for loading policies
type LoadPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy source (file path, URL, or inline)
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Source type
	SourceType SourceType `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=authz.v1.SourceType" json:"source_type,omitempty"`
	// Inline policy content (if source_type is INLINE)
	Policies      []*Policy `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPoliciesRequest) Reset() {
	*x = LoadPoliciesRequest{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPoliciesRequest) ProtoMessage() {}

func (x *LoadPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPoliciesRequest.ProtoReflect.Descriptor instead.
func (*LoadPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{12}
}

func (x *LoadPoliciesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LoadPoliciesRequest) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *LoadPoliciesRequest) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

// Policy represents an authorization policy
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Policy name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Resource kind this policy applies to
	ResourceKind string `protobuf:"bytes,3,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	// Policy rules
	Rules []*Rule `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	// Hierarchical scope where this policy applies (e.g., "acme.corp.engineering")
	Scope string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	// Phase 3: Marks this as a principal policy
	PrincipalPolicy bool `protobuf:"varint,10,opt,name=principal_policy,json=principalPolicy,proto3" json:"principal_policy,omitempty"`
	// Phase 3: Principal selector for principal policies
	Principal *PrincipalSelector `protobuf:"bytes,11,opt,name=principal,proto3" json:"principal,omitempty"`
	// Phase 3: Resource selectors for principal policies
	Resources     []*ResourceSelector `protobuf:"bytes,12,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{13}
}

func (x *Policy) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *Policy) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Policy) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Policy) GetPrincipalPolicy() bool {
	if x != nil {
		return x.PrincipalPolicy
	}
	return false
}

func (x *Policy) GetPrincipal() *PrincipalSelector {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *Policy) GetResources() []*ResourceSelector {
	if x != nil {
		return x.Resources
	}
	return nil
}

// Rule represents a single authorization rule
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rule name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Actions this rule applies to
	Actions []string `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	// Effect if rule matches
	Effect Effect `protobuf:"varint,3,opt,name=effect,proto3,enum=authz.v1.Effect" json:"effect,omitempty"`
	// CEL condition (optional)
	Condition string `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	// Roles that can match this rule
	Roles []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	// Derived roles references
	DerivedRoles  []string `protobuf:"bytes,6,rep,name=derived_roles,json=derivedRoles,proto3" json:"derived_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{14}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Rule) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

func (x *Rule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Rule) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Rule) GetDerivedRoles() []string {
	if x != nil {
		return x.DerivedRoles
	}
	return nil
}

// LoadPoliciesResponse
type LoadPoliciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of policies loaded
	PoliciesLoaded int32 `protobuf:"varint,1,opt,name=policies_loaded,json=policiesLoaded,proto3" json:"policies_loaded,omitempty"`
	// Any validation errors
	Errors        []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPoliciesResponse) Reset() {
	*x = LoadPoliciesResponse{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPoliciesResponse) ProtoMessage() {}

func (x *LoadPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPoliciesResponse.ProtoReflect.Descriptor instead.
func (*LoadPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{15}
}

func (x *LoadPoliciesResponse) GetPoliciesLoaded() int32 {
	if x != nil {
		return x.PoliciesLoaded
	}
	return 0
}

func (x *LoadPoliciesResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ReloadPoliciesRequest triggers policy reload
type ReloadPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Force reload even if no changes detected
	Force         bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPoliciesRequest) Reset() {
	*x = ReloadPoliciesRequest{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPoliciesRequest) ProtoMessage() {}

func (x *ReloadPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ReloadPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{16}
}

func (x *ReloadPoliciesRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// ReloadPoliciesResponse
type ReloadPoliciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether reload was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of policies after reload
	PolicyCount int32 `protobuf:"varint,2,opt,name=policy_count,json=policyCount,proto3" json:"policy_count,omitempty"`
	// Reload duration (milliseconds)
	ReloadDurationMs float64 `protobuf:"fixed64,3,opt,name=reload_duration_ms,json=reloadDurationMs,proto3" json:"reload_duration_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReloadPoliciesResponse) Reset() {
	*x = ReloadPoliciesResponse{}
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPoliciesResponse) ProtoMessage() {}

func (x *ReloadPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_authz_v1_authz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ReloadPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_authz_v1_authz_proto_rawDescGZIP(), []int{17}
}

func (x *ReloadPoliciesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadPoliciesResponse) GetPolicyCount() int32 {
	if x != nil {
		return x.PolicyCount
	}
	return 0
}

func (x *ReloadPoliciesResponse) GetReloadDurationMs() float64 {
	if x != nil {
		return x.ReloadDurationMs
	}
	return 0
}

var File_api_proto_authz_v1_authz_proto protoreflect.FileDescriptor

const file_api_proto_authz_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/authz/v1/authz.proto\x12\bauthz.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x88\x02\n" +
	"\fCheckRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x121\n" +
	"\tprincipal\x18\x02 \x01(\v2\x13.authz.v1.PrincipalR\tprincipal\x12.\n" +
	"\bresource\x18\x03 \x01(\v2\x12.authz.v1.ResourceR\bresource\x12\x18\n" +
	"\aactions\x18\x04 \x03(\tR\aactions\x121\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructR\acontext\x12)\n" +
	"\x10include_metadata\x18\x06 \x01(\bR\x0fincludeMetadata\"\x80\x01\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x127\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"}\n" +
	"\bResource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x127\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\xfa\x01\n" +
	"\rCheckResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12>\n" +
	"\aresults\x18\x02 \x03(\v2$.authz.v1.CheckResponse.ResultsEntryR\aresults\x126\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.authz.v1.ResponseMetadataR\bmetadata\x1aR\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.authz.v1.ActionResultR\x05value:\x028\x01\"\xed\x01\n" +
	"\fActionResult\x12(\n" +
	"\x06effect\x18\x01 \x01(\x0e2\x10.authz.v1.EffectR\x06effect\x12\x16\n" +
	"\x06policy\x18\x02 \x01(\tR\x06policy\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x18\n" +
	"\amatched\x18\x04 \x01(\bR\amatched\x124\n" +
	"\x04meta\x18\x05 \x03(\v2 .authz.v1.ActionResult.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x02\n" +
	"\x10ResponseMetadata\x124\n" +
	"\x16evaluation_duration_us\x18\x01 \x01(\x01R\x14evaluationDurationUs\x12-\n" +
	"\x12policies_evaluated\x18\x02 \x01(\x05R\x11policiesEvaluated\x12)\n" +
	"\x10matched_policies\x18\x03 \x03(\tR\x0fmatchedPolicies\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\x12D\n" +
	"\x10scope_resolution\x18\x05 \x01(\v2\x19.authz.v1.ScopeResolutionR\x0fscopeResolution\x12G\n" +
	"\x11policy_resolution\x18\x06 \x01(\v2\x1a.authz.v1.PolicyResolutionR\x10policyResolution\"\x97\x01\n" +
	"\x0fScopeResolution\x12#\n" +
	"\rmatched_scope\x18\x01 \x01(\tR\fmatchedScope\x12+\n" +
	"\x11inheritance_chain\x18\x02 \x03(\tR\x10inheritanceChain\x122\n" +
	"\x15scoped_policy_matched\x18\x03 \x01(\bR\x13scopedPolicyMatched\"O\n" +
	"\x11PrincipalSelector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\"<\n" +
	"\x10ResourceSelector\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"\xfd\x01\n" +
	"\x10PolicyResolution\x12<\n" +
	"\x1aprincipal_policies_matched\x18\x01 \x01(\bR\x18principalPoliciesMatched\x12:\n" +
	"\x19resource_policies_matched\x18\x02 \x01(\bR\x17resourcePoliciesMatched\x12)\n" +
	"\x10evaluation_order\x18\x03 \x03(\tR\x0fevaluationOrder\x12D\n" +
	"\x10scope_resolution\x18\x04 \x01(\v2\x19.authz.v1.ScopeResolutionR\x0fscopeResolution\"G\n" +
	"\x11CheckBatchRequest\x122\n" +
	"\brequests\x18\x01 \x03(\v2\x16.authz.v1.CheckRequestR\brequests\"w\n" +
	"\x12CheckBatchResponse\x125\n" +
	"\tresponses\x18\x01 \x03(\v2\x17.authz.v1.CheckResponseR\tresponses\x12*\n" +
	"\x11total_duration_us\x18\x02 \x01(\x01R\x0ftotalDurationUs\"\x92\x01\n" +
	"\x13LoadPoliciesRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x125\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x14.authz.v1.SourceTypeR\n" +
	"sourceType\x12,\n" +
	"\bpolicies\x18\x03 \x03(\v2\x10.authz.v1.PolicyR\bpolicies\"\xbe\x02\n" +
	"\x06Policy\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rresource_kind\x18\x03 \x01(\tR\fresourceKind\x12$\n" +
	"\x05rules\x18\x04 \x03(\v2\x0e.authz.v1.RuleR\x05rules\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12)\n" +
	"\x10principal_policy\x18\n" +
	" \x01(\bR\x0fprincipalPolicy\x129\n" +
	"\tprincipal\x18\v \x01(\v2\x1b.authz.v1.PrincipalSelectorR\tprincipal\x128\n" +
	"\tresources\x18\f \x03(\v2\x1a.authz.v1.ResourceSelectorR\tresources\"\xb7\x01\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\x12(\n" +
	"\x06effect\x18\x03 \x01(\x0e2\x10.authz.v1.EffectR\x06effect\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12#\n" +
	"\rderived_roles\x18\x06 \x03(\tR\fderivedRoles\"W\n" +
	"\x14LoadPoliciesResponse\x12'\n" +
	"\x0fpolicies_loaded\x18\x01 \x01(\x05R\x0epoliciesLoaded\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"-\n" +
	"\x15ReloadPoliciesRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\x83\x01\n" +
	"\x16ReloadPoliciesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpolicy_count\x18\x02 \x01(\x05R\vpolicyCount\x12,\n" +
	"\x12reload_duration_ms\x18\x03 \x01(\x01R\x10reloadDurationMs*C\n" +
	"\x06Effect\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fEFFECT_ALLOW\x10\x01\x12\x0f\n" +
	"\vEFFECT_DENY\x10\x02*l\n" +
	"\n" +
	"SourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SOURCE_TYPE_FILE\x10\x01\x12\x13\n" +
	"\x0fSOURCE_TYPE_URL\x10\x02\x12\x16\n" +
	"\x12SOURCE_TYPE_INLINE\x10\x032\xf9\x02\n" +
	"\fAuthzService\x128\n" +
	"\x05Check\x12\x16.authz.v1.CheckRequest\x1a\x17.authz.v1.CheckResponse\x12G\n" +
	"\n" +
	"CheckBatch\x12\x1b.authz.v1.CheckBatchRequest\x1a\x1c.authz.v1.CheckBatchResponse\x12B\n" +
	"\vCheckStream\x12\x16.authz.v1.CheckRequest\x1a\x17.authz.v1.CheckResponse(\x010\x01\x12M\n" +
	"\fLoadPolicies\x12\x1d.authz.v1.LoadPoliciesRequest\x1a\x1e.authz.v1.LoadPoliciesResponse\x12S\n" +
	"\x0eReloadPolicies\x12\x1f.authz.v1.ReloadPoliciesRequest\x1a .authz.v1.ReloadPoliciesResponseB<Z:github.com/authz-engine/go-core/api/proto/authz/v1;authzv1b\x06proto3"

var (
	file_api_proto_authz_v1_authz_proto_rawDescOnce sync.Once
	file_api_proto_authz_v1_authz_proto_rawDescData []byte
)

func file_api_proto_authz_v1_authz_proto_rawDescGZIP() []byte {
	file_api_proto_authz_v1_authz_proto_rawDescOnce.Do(func() {
		file_api_proto_authz_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_authz_v1_authz_proto_rawDesc), len(file_api_proto_authz_v1_authz_proto_rawDesc)))
	})
	return file_api_proto_authz_v1_authz_proto_rawDescData
}

var file_api_proto_authz_v1_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_authz_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_authz_v1_authz_proto_goTypes = []any{
	(Effect)(0),                    // 0: authz.v1.Effect
	(SourceType)(0),                // 1: authz.v1.SourceType
	(*CheckRequest)(nil),           // 2: authz.v1.CheckRequest
	(*Principal)(nil),              // 3: authz.v1.Principal
	(*Resource)(nil),               // 4: authz.v1.Resource
	(*CheckResponse)(nil),          // 5: authz.v1.CheckResponse
	(*ActionResult)(nil),           // 6: authz.v1.ActionResult
	(*ResponseMetadata)(nil),       // 7: authz.v1.ResponseMetadata
	(*ScopeResolution)(nil),        // 8: authz.v1.ScopeResolution
	(*PrincipalSelector)(nil),      // 9: authz.v1.PrincipalSelector
	(*ResourceSelector)(nil),       // 10: authz.v1.ResourceSelector
	(*PolicyResolution)(nil),       // 11: authz.v1.PolicyResolution
	(*CheckBatchRequest)(nil),      // 12: authz.v1.CheckBatchRequest
	(*CheckBatchResponse)(nil),     // 13: authz.v1.CheckBatchResponse
	(*LoadPoliciesRequest)(nil),    // 14: authz.v1.LoadPoliciesRequest
	(*Policy)(nil),                 // 15: authz.v1.Policy
	(*Rule)(nil),                   // 16: authz.v1.Rule
	(*LoadPoliciesResponse)(nil),   // 17: authz.v1.LoadPoliciesResponse
	(*ReloadPoliciesRequest)(nil),  // 18: authz.v1.ReloadPoliciesRequest
	(*ReloadPoliciesResponse)(nil), // 19: authz.v1.ReloadPoliciesResponse
	nil,                            // 20: authz.v1.CheckResponse.ResultsEntry
	nil,                            // 21: authz.v1.ActionResult.MetaEntry
	(*structpb.Struct)(nil),        // 22: google.protobuf.Struct
}
var file_api_proto_authz_v1_authz_proto_depIdxs = []int32{
	3,  // 0: authz.v1.CheckRequest.principal:type_name -> authz.v1.Principal
	4,  // 1: authz.v1.CheckRequest.resource:type_name -> authz.v1.Resource
	22, // 2: authz.v1.CheckRequest.context:type_name -> google.protobuf.Struct
	22, // 3: authz.v1.Principal.attributes:type_name -> google.protobuf.Struct
	22, // 4: authz.v1.Resource.attributes:type_name -> google.protobuf.Struct
	20, // 5: authz.v1.CheckResponse.results:type_name -> authz.v1.CheckResponse.ResultsEntry
	7,  // 6: authz.v1.CheckResponse.metadata:type_name -> authz.v1.ResponseMetadata
	0,  // 7: authz.v1.ActionResult.effect:type_name -> authz.v1.Effect
	21, // 8: authz.v1.ActionResult.meta:type_name -> authz.v1.ActionResult.MetaEntry
	8,  // 9: authz.v1.ResponseMetadata.scope_resolution:type_name -> authz.v1.ScopeResolution
	11, // 10: authz.v1.ResponseMetadata.policy_resolution:type_name -> authz.v1.PolicyResolution
	8,  // 11: authz.v1.PolicyResolution.scope_resolution:type_name -> authz.v1.ScopeResolution
	2,  // 12: authz.v1.CheckBatchRequest.requests:type_name -> authz.v1.CheckRequest
	5,  // 13: authz.v1.CheckBatchResponse.responses:type_name -> authz.v1.CheckResponse
	1,  // 14: authz.v1.LoadPoliciesRequest.source_type:type_name -> authz.v1.SourceType
	15, // 15: authz.v1.LoadPoliciesRequest.policies:type_name -> authz.v1.Policy
	16, // 16: authz.v1.Policy.rules:type_name -> authz.v1.Rule
	9,  // 17: authz.v1.Policy.principal:type_name -> authz.v1.PrincipalSelector
	10, // 18: authz.v1.Policy.resources:type_name -> authz.v1.ResourceSelector
	0,  // 19: authz.v1.Rule.effect:type_name -> authz.v1.Effect
	6,  // 20: authz.v1.CheckResponse.ResultsEntry.value:type_name -> authz.v1.ActionResult
	2,  // 21: authz.v1.AuthzService.Check:input_type -> authz.v1.CheckRequest
	12, // 22: authz.v1.AuthzService.CheckBatch:input_type -> authz.v1.CheckBatchRequest
	2,  // 23: authz.v1.AuthzService.CheckStream:input_type -> authz.v1.CheckRequest
	14, // 24: authz.v1.AuthzService.LoadPolicies:input_type -> authz.v1.LoadPoliciesRequest
	18, // 25: authz.v1.AuthzService.ReloadPolicies:input_type -> authz.v1.ReloadPoliciesRequest
	5,  // 26: authz.v1.AuthzService.Check:output_type -> authz.v1.CheckResponse
	13, // 27: authz.v1.AuthzService.CheckBatch:output_type -> authz.v1.CheckBatchResponse
	5,  // 28: authz.v1.AuthzService.CheckStream:output_type -> authz.v1.CheckResponse
	17, // 29: authz.v1.AuthzService.LoadPolicies:output_type -> authz.v1.LoadPoliciesResponse
	19, // 30: authz.v1.AuthzService.ReloadPolicies:output_type -> authz.v1.ReloadPoliciesResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_authz_v1_authz_proto_init() }
func file_api_proto_authz_v1_authz_proto_init() {
	if File_api_proto_authz_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_authz_v1_authz_proto_rawDesc), len(file_api_proto_authz_v1_authz_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_authz_v1_authz_proto_goTypes,
		DependencyIndexes: file_api_proto_authz_v1_authz_proto_depIdxs,
		EnumInfos:         file_api_proto_authz_v1_authz_proto_enumTypes,
		MessageInfos:      file_api_proto_authz_v1_authz_proto_msgTypes,
	}.Build()
	File_api_proto_authz_v1_authz_proto = out.File
	file_api_proto_authz_v1_authz_proto_goTypes = nil
	file_api_proto_authz_v1_authz_proto_depIdxs = nil
}
