// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.0
// source: authz/v1/authz.proto

package authzv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or higher.
const _ = grpc.SupportPackageIsVersion7

// AuthzServiceClient is the client API for AuthzService service.
//
// For semantics around ctx use and closing/cleanup resources, consult the grpc package documentation on using Contexts.
type AuthzServiceClient interface {
	// Check performs a single authorization check
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// CheckBatch performs multiple authorization checks in parallel
	CheckBatch(ctx context.Context, in *CheckBatchRequest, opts ...grpc.CallOption) (*CheckBatchResponse, error)
	// CheckStream provides bidirectional streaming for high-throughput scenarios
	CheckStream(ctx context.Context, opts ...grpc.CallOption) (AuthzService_CheckStreamClient, error)
	// LoadPolicies loads policies from a source
	LoadPolicies(ctx context.Context, in *LoadPoliciesRequest, opts ...grpc.CallOption) (*LoadPoliciesResponse, error)
	// ReloadPolicies triggers a policy reload
	ReloadPolicies(ctx context.Context, in *ReloadPoliciesRequest, opts ...grpc.CallOption) (*ReloadPoliciesResponse, error)
}

type authzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthzServiceClient(cc grpc.ClientConnInterface) AuthzServiceClient {
	return &authzServiceClient{cc}
}

func (c *authzServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/authz.v1.AuthzService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) CheckBatch(ctx context.Context, in *CheckBatchRequest, opts ...grpc.CallOption) (*CheckBatchResponse, error) {
	out := new(CheckBatchResponse)
	err := c.cc.Invoke(ctx, "/authz.v1.AuthzService/CheckBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) CheckStream(ctx context.Context, opts ...grpc.CallOption) (AuthzService_CheckStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AuthzService_ServiceDesc.Streams[0], "/authz.v1.AuthzService/CheckStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &authzServiceCheckStreamClient{stream}
	return x, nil
}

func (c *authzServiceClient) LoadPolicies(ctx context.Context, in *LoadPoliciesRequest, opts ...grpc.CallOption) (*LoadPoliciesResponse, error) {
	out := new(LoadPoliciesResponse)
	err := c.cc.Invoke(ctx, "/authz.v1.AuthzService/LoadPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) ReloadPolicies(ctx context.Context, in *ReloadPoliciesRequest, opts ...grpc.CallOption) (*ReloadPoliciesResponse, error) {
	out := new(ReloadPoliciesResponse)
	err := c.cc.Invoke(ctx, "/authz.v1.AuthzService/ReloadPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type AuthzService_CheckStreamClient interface {
	Send(*CheckRequest) error
	Recv() (*CheckResponse, error)
	grpc.ClientStream
}

type authzServiceCheckStreamClient struct {
	grpc.ClientStream
}

func (x *authzServiceCheckStreamClient) Send(m *CheckRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *authzServiceCheckStreamClient) Recv() (*CheckResponse, error) {
	m := new(CheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthzServiceServer is the server API for AuthzService service.
// All implementations must embed UnimplementedAuthzServiceServer
// for forward compatibility
type AuthzServiceServer interface {
	// Check performs a single authorization check
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// CheckBatch performs multiple authorization checks in parallel
	CheckBatch(context.Context, *CheckBatchRequest) (*CheckBatchResponse, error)
	// CheckStream provides bidirectional streaming for high-throughput scenarios
	CheckStream(AuthzService_CheckStreamServer) error
	// LoadPolicies loads policies from a source
	LoadPolicies(context.Context, *LoadPoliciesRequest) (*LoadPoliciesResponse, error)
	// ReloadPolicies triggers a policy reload
	ReloadPolicies(context.Context, *ReloadPoliciesRequest) (*ReloadPoliciesResponse, error)
	mustEmbedUnimplementedAuthzServiceServer()
}

// UnimplementedAuthzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthzServiceServer struct {
}

func (UnimplementedAuthzServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAuthzServiceServer) CheckBatch(context.Context, *CheckBatchRequest) (*CheckBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBatch not implemented")
}
func (UnimplementedAuthzServiceServer) CheckStream(AuthzService_CheckStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckStream not implemented")
}
func (UnimplementedAuthzServiceServer) LoadPolicies(context.Context, *LoadPoliciesRequest) (*LoadPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadPolicies not implemented")
}
func (UnimplementedAuthzServiceServer) ReloadPolicies(context.Context, *ReloadPoliciesRequest) (*ReloadPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPolicies not implemented")
}
func (UnimplementedAuthzServiceServer) mustEmbedUnimplementedAuthzServiceServer() {}

// UnsafeAuthzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as adding methods to AuthzServiceServer will
// result in compilation errors.
type UnsafeAuthzServiceServer interface {
	mustEmbedUnimplementedAuthzServiceServer()
}

func RegisterAuthzServiceServer(s grpc.ServiceRegistrar, srv AuthzServiceServer) {
	s.RegisterService(&AuthzService_ServiceDesc, srv)
}

func _AuthzService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authz.v1.AuthzService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_CheckBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).CheckBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authz.v1.AuthzService/CheckBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).CheckBatch(ctx, req.(*CheckBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_CheckStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthzServiceServer).CheckStream(&authzServiceCheckStreamServer{stream})
}

type AuthzService_CheckStreamServer interface {
	Send(*CheckResponse) error
	Recv() (*CheckRequest, error)
	grpc.ServerStream
}

type authzServiceCheckStreamServer struct {
	grpc.ServerStream
}

func (x *authzServiceCheckStreamServer) Send(m *CheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *authzServiceCheckStreamServer) Recv() (*CheckRequest, error) {
	m := new(CheckRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AuthzService_LoadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).LoadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authz.v1.AuthzService/LoadPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).LoadPolicies(ctx, req.(*LoadPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_ReloadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).ReloadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authz.v1.AuthzService/ReloadPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).ReloadPolicies(ctx, req.(*ReloadPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthzService_ServiceDesc is the grpc.ServiceDesc for AuthzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be used by the generated client and server code.
var AuthzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authz.v1.AuthzService",
	HandlerType: (*AuthzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AuthzService_Check_Handler,
		},
		{
			MethodName: "CheckBatch",
			Handler:    _AuthzService_CheckBatch_Handler,
		},
		{
			MethodName: "LoadPolicies",
			Handler:    _AuthzService_LoadPolicies_Handler,
		},
		{
			MethodName: "ReloadPolicies",
			Handler:    _AuthzService_ReloadPolicies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckStream",
			Handler:       _AuthzService_CheckStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "authz/v1/authz.proto",
}
