// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/proto/authz/v1/authz.proto

package authzv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthzService_Check_FullMethodName          = "/authz.v1.AuthzService/Check"
	AuthzService_CheckBatch_FullMethodName     = "/authz.v1.AuthzService/CheckBatch"
	AuthzService_CheckStream_FullMethodName    = "/authz.v1.AuthzService/CheckStream"
	AuthzService_LoadPolicies_FullMethodName   = "/authz.v1.AuthzService/LoadPolicies"
	AuthzService_ReloadPolicies_FullMethodName = "/authz.v1.AuthzService/ReloadPolicies"
)

// AuthzServiceClient is the client API for AuthzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthzService provides high-performance authorization checking
type AuthzServiceClient interface {
	// Check performs a single authorization check
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// CheckBatch performs multiple authorization checks in parallel
	CheckBatch(ctx context.Context, in *CheckBatchRequest, opts ...grpc.CallOption) (*CheckBatchResponse, error)
	// CheckStream provides bidirectional streaming for high-throughput scenarios
	CheckStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CheckRequest, CheckResponse], error)
	// LoadPolicies loads policies from a source
	LoadPolicies(ctx context.Context, in *LoadPoliciesRequest, opts ...grpc.CallOption) (*LoadPoliciesResponse, error)
	// ReloadPolicies triggers a policy reload
	ReloadPolicies(ctx context.Context, in *ReloadPoliciesRequest, opts ...grpc.CallOption) (*ReloadPoliciesResponse, error)
}

type authzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthzServiceClient(cc grpc.ClientConnInterface) AuthzServiceClient {
	return &authzServiceClient{cc}
}

func (c *authzServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, AuthzService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) CheckBatch(ctx context.Context, in *CheckBatchRequest, opts ...grpc.CallOption) (*CheckBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBatchResponse)
	err := c.cc.Invoke(ctx, AuthzService_CheckBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) CheckStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CheckRequest, CheckResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthzService_ServiceDesc.Streams[0], AuthzService_CheckStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CheckRequest, CheckResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthzService_CheckStreamClient = grpc.BidiStreamingClient[CheckRequest, CheckResponse]

func (c *authzServiceClient) LoadPolicies(ctx context.Context, in *LoadPoliciesRequest, opts ...grpc.CallOption) (*LoadPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadPoliciesResponse)
	err := c.cc.Invoke(ctx, AuthzService_LoadPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) ReloadPolicies(ctx context.Context, in *ReloadPoliciesRequest, opts ...grpc.CallOption) (*ReloadPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadPoliciesResponse)
	err := c.cc.Invoke(ctx, AuthzService_ReloadPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthzServiceServer is the server API for AuthzService service.
// All implementations must embed UnimplementedAuthzServiceServer
// for forward compatibility.
//
// AuthzService provides high-performance authorization checking
type AuthzServiceServer interface {
	// Check performs a single authorization check
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// CheckBatch performs multiple authorization checks in parallel
	CheckBatch(context.Context, *CheckBatchRequest) (*CheckBatchResponse, error)
	// CheckStream provides bidirectional streaming for high-throughput scenarios
	CheckStream(grpc.BidiStreamingServer[CheckRequest, CheckResponse]) error
	// LoadPolicies loads policies from a source
	LoadPolicies(context.Context, *LoadPoliciesRequest) (*LoadPoliciesResponse, error)
	// ReloadPolicies triggers a policy reload
	ReloadPolicies(context.Context, *ReloadPoliciesRequest) (*ReloadPoliciesResponse, error)
	mustEmbedUnimplementedAuthzServiceServer()
}

// UnimplementedAuthzServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthzServiceServer struct{}

func (UnimplementedAuthzServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAuthzServiceServer) CheckBatch(context.Context, *CheckBatchRequest) (*CheckBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBatch not implemented")
}
func (UnimplementedAuthzServiceServer) CheckStream(grpc.BidiStreamingServer[CheckRequest, CheckResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CheckStream not implemented")
}
func (UnimplementedAuthzServiceServer) LoadPolicies(context.Context, *LoadPoliciesRequest) (*LoadPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadPolicies not implemented")
}
func (UnimplementedAuthzServiceServer) ReloadPolicies(context.Context, *ReloadPoliciesRequest) (*ReloadPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPolicies not implemented")
}
func (UnimplementedAuthzServiceServer) mustEmbedUnimplementedAuthzServiceServer() {}
func (UnimplementedAuthzServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuthzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthzServiceServer will
// result in compilation errors.
type UnsafeAuthzServiceServer interface {
	mustEmbedUnimplementedAuthzServiceServer()
}

func RegisterAuthzServiceServer(s grpc.ServiceRegistrar, srv AuthzServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthzServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthzService_ServiceDesc, srv)
}

func _AuthzService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_CheckBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).CheckBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_CheckBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).CheckBatch(ctx, req.(*CheckBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_CheckStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthzServiceServer).CheckStream(&grpc.GenericServerStream[CheckRequest, CheckResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthzService_CheckStreamServer = grpc.BidiStreamingServer[CheckRequest, CheckResponse]

func _AuthzService_LoadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).LoadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_LoadPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).LoadPolicies(ctx, req.(*LoadPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_ReloadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).ReloadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_ReloadPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).ReloadPolicies(ctx, req.(*ReloadPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthzService_ServiceDesc is the grpc.ServiceDesc for AuthzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authz.v1.AuthzService",
	HandlerType: (*AuthzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AuthzService_Check_Handler,
		},
		{
			MethodName: "CheckBatch",
			Handler:    _AuthzService_CheckBatch_Handler,
		},
		{
			MethodName: "LoadPolicies",
			Handler:    _AuthzService_LoadPolicies_Handler,
		},
		{
			MethodName: "ReloadPolicies",
			Handler:    _AuthzService_ReloadPolicies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckStream",
			Handler:       _AuthzService_CheckStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/authz/v1/authz.proto",
}
